# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20540491b2233d19be792c07e74b9ff13e3b8e24c12582c5a95dd2fce9f67e414409c1d05f6a4cc8e5533b60a4d84185d98f080f69ef8c137be4a48d8552f7a9

test:
  secret_key_base: 1c361736f153f9ae4a70a6f8dcc1d5b93c8a45a8ab19c896a1680c8ae8ed74c0a7631822e74ac5df8a440350bab87872f46fbcce73df47c31e067d4375f95b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
